version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "04:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: serverless-webpack
    versions:
    - 5.3.5
    - 5.4.0
    - 5.4.1
  - dependency-name: webpack-node-externals
    versions:
    - 2.5.2
  - dependency-name: lodash
    versions:
    - 4.17.20
  - dependency-name: elliptic
    versions:
    - 6.5.3
