service: webpack-template

provider:
  name: aws
  runtime: nodejs6.10

functions:
  hello:
    handler: handler.hello
    events:
      - http: get hello
plugins:
  - serverless-webpack

custom:
  webpackIncludeModules: true
